### ISSUE TITLE
FBD Free Body Diagram -- directory node

### ISSUE THREAD

**Issue by JohnDenker** [ericmazur/PnPbook#90]
This is a catalog aka directory node aka task list.  It contains pointers to several issues related to free body diagrams.
- [x] #91 (-: Use a separate FBD for each object :-)
- [ ] #92 FBD rigid body ... or not
- [ ] #93 FBD CM concept ... or not
- [ ] #94 reference marks : form and function
- [ ] #95 coordinate system versus vector basis
